// <auto-generated />
using System;
using ClaimsModule.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClaimsModule.Persistence.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    partial class ClaimsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClaimsModule.Domain.Entities.CauseOfLossCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PerilCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CauseOfLossCodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("23f86f7e-861e-c713-0142-0542fae2fcaa"),
                            Code = "COL-FIRE",
                            IsActive = true,
                            Name = "Fire",
                            PerilCategory = "Property",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("7540981d-8a1e-7ac9-6a82-f08d37c07678"),
                            Code = "COL-FLOOD",
                            IsActive = true,
                            Name = "Flood",
                            PerilCategory = "Weather",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("3f36627b-f5e2-e706-603e-e810376ae345"),
                            Code = "COL-THEFT",
                            IsActive = true,
                            Name = "Theft",
                            PerilCategory = "Crime",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("9f2502dc-2f98-c3a9-29ca-391ba3e082af"),
                            Code = "COL-VEH-COL",
                            IsActive = true,
                            Name = "Vehicle Collision",
                            PerilCategory = "Auto",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("af53c41d-96c7-e607-0bca-4e5059c100ef"),
                            Code = "COL-VEH-COMP",
                            IsActive = true,
                            Name = "Vehicle Comprehensive",
                            PerilCategory = "Auto",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = new Guid("8d5c10c9-40a9-e289-3230-09aa954e9d2d"),
                            Code = "COL-LIAB",
                            IsActive = true,
                            Name = "Third Party Liability",
                            PerilCategory = "Liability",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = new Guid("aecc8d6a-f9d1-602f-0f61-05161963a438"),
                            Code = "COL-EQUIP",
                            IsActive = true,
                            Name = "Equipment Breakdown",
                            PerilCategory = "Equipment",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = new Guid("f5a8002e-dbae-a29e-c166-78757f354c2c"),
                            Code = "COL-WIND",
                            IsActive = true,
                            Name = "Wind / Storm",
                            PerilCategory = "Weather",
                            SortOrder = 80
                        },
                        new
                        {
                            Id = new Guid("e874757c-3ee2-4d51-611e-b8a4b20c28bb"),
                            Code = "COL-INJURY",
                            IsActive = true,
                            Name = "Bodily Injury",
                            PerilCategory = "Liability",
                            SortOrder = 90
                        },
                        new
                        {
                            Id = new Guid("0ede865f-afdd-884f-32e5-e71f6d514c33"),
                            Code = "COL-OTHER",
                            IsActive = true,
                            Name = "Other / Unknown",
                            PerilCategory = "General",
                            SortOrder = 100
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedHandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ClosureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ManagerOverrideApplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ReportedDate")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedHandlerId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("Status");

                    b.HasIndex("OrganisationId", "ClaimNumber")
                        .IsUnique();

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("ClaimId", "CreatedAt");

                    b.HasIndex("RelatedEntityId")
                        .IsUnique()
                        .HasFilter("[EventType] = 'GL_POSTING_SIMULATED'");

                    b.ToTable("ClaimAuditLog", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimDocuments", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimNumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CurrentValue")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "Year")
                        .IsUnique();

                    b.ToTable("ClaimNumberSequences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("63f0c1f2-a7b2-5d3e-240a-9d64828f9e6e"),
                            CurrentValue = 0L,
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("5f4023ec-00d9-5943-f7b0-01a501f9b8f7"),
                            CurrentValue = 0L,
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("f451fb0f-bebf-c15b-2330-770ce18b438c"),
                            CurrentValue = 0L,
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("e1f56050-d0b4-253b-6883-5263b1c1938f"),
                            CurrentValue = 0L,
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("e061b649-dde3-2e8e-c570-61d289301dc0"),
                            CurrentValue = 0L,
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2028
                        },
                        new
                        {
                            Id = new Guid("9a277f30-e5b8-3667-b0b1-ebe3427ade19"),
                            CurrentValue = 0L,
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2029
                        },
                        new
                        {
                            Id = new Guid("2a401f18-7699-6ae9-fad4-ad02c5baa9b1"),
                            CurrentValue = 0L,
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2030
                        },
                        new
                        {
                            Id = new Guid("2f571518-fcb2-c600-394b-65a623093b26"),
                            CurrentValue = 0L,
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2031
                        },
                        new
                        {
                            Id = new Guid("818895e9-2705-1bd4-5a90-19aea13bf92c"),
                            CurrentValue = 0L,
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2032
                        },
                        new
                        {
                            Id = new Guid("d6928ae7-0fd5-f44c-a360-1eeaa0571df5"),
                            CurrentValue = 0L,
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2033
                        },
                        new
                        {
                            Id = new Guid("08b02e71-d0ed-83d2-c009-c2a0938ffc58"),
                            CurrentValue = 0L,
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2034
                        },
                        new
                        {
                            Id = new Guid("afc92be1-4632-f977-f3c9-8fc47302b8fe"),
                            CurrentValue = 0L,
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2035
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimParty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartyRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimParties", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimReserveComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<decimal>("CurrentAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("ClaimId", "Component");

                    b.ToTable("ClaimReserveComponents", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimRiskObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AssetReference")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DamageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimRiskObjects", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimStatusTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequiredRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FromStatus", "ToStatus")
                        .IsUnique();

                    b.ToTable("ClaimStatusTransitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("15b98e75-4afc-ba8c-8ae9-e9ca20708c9d"),
                            FromStatus = "Draft",
                            ToStatus = "Open"
                        },
                        new
                        {
                            Id = new Guid("842d4c33-ac02-3d4b-f2bd-0e6f7f58fd68"),
                            FromStatus = "Open",
                            ToStatus = "UnderInvestigation"
                        },
                        new
                        {
                            Id = new Guid("0ab35873-474c-bb1f-3baa-7ace617d03c8"),
                            FromStatus = "Open",
                            ToStatus = "PendingPayment"
                        },
                        new
                        {
                            Id = new Guid("7203b252-7106-b7b2-23b9-cc14360ad7c5"),
                            FromStatus = "Open",
                            ToStatus = "Closed"
                        },
                        new
                        {
                            Id = new Guid("eaac4a84-7cf4-9c56-790b-c61225c1f7b3"),
                            FromStatus = "Open",
                            ToStatus = "Withdrawn"
                        },
                        new
                        {
                            Id = new Guid("4a45b070-a8b7-9999-53a2-b0a0710b1aac"),
                            FromStatus = "UnderInvestigation",
                            ToStatus = "Open"
                        },
                        new
                        {
                            Id = new Guid("5c83eb55-a453-fe99-f6e6-497539a85cec"),
                            FromStatus = "UnderInvestigation",
                            ToStatus = "PendingPayment"
                        },
                        new
                        {
                            Id = new Guid("4a9cae82-d2a4-9825-3c6a-e0ec55fb4247"),
                            FromStatus = "UnderInvestigation",
                            ToStatus = "Closed"
                        },
                        new
                        {
                            Id = new Guid("98802910-00dd-ecd9-86f1-cf156732f01b"),
                            FromStatus = "UnderInvestigation",
                            ToStatus = "Withdrawn"
                        },
                        new
                        {
                            Id = new Guid("b39c90d3-22d7-3822-93ef-1bb289d880e4"),
                            FromStatus = "PendingPayment",
                            ToStatus = "Closed"
                        },
                        new
                        {
                            Id = new Guid("943e1a50-9725-026b-6ace-9e33b4d66427"),
                            FromStatus = "Closed",
                            RequiredRole = "Supervisor",
                            ToStatus = "Reopened"
                        },
                        new
                        {
                            Id = new Guid("9f71666c-e9b6-1358-12c7-ce5b4b8b56b5"),
                            FromStatus = "Reopened",
                            ToStatus = "Open"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.LossEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CauseOfLossCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<decimal?>("EstimatedLossAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LossDate")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("LossDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LossLocation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PoliceReportNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("ReportDate")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CauseOfLossCode");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.ToTable("LossEvents", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CoverageTypes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "PolicyNumber")
                        .IsUnique();

                    b.ToTable("Policies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e71f5e6-5993-9788-964e-5c080745dd72"),
                            ClientName = "Meridian Transport LLC",
                            CoverageTypes = "Vehicle,Cargo",
                            EffectiveDate = new DateOnly(2024, 1, 1),
                            ExpirationDate = new DateOnly(2026, 12, 31),
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2024-001001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("1947fcaf-f596-9f66-7d69-c4c8429c82df"),
                            ClientName = "Harborview Properties Inc",
                            CoverageTypes = "Property,Liability",
                            EffectiveDate = new DateOnly(2024, 6, 1),
                            ExpirationDate = new DateOnly(2026, 5, 31),
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2024-001002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0cf86c04-2a25-343e-2c4f-4fa6c7e0a02b"),
                            ClientName = "Coastal Builders Group",
                            CoverageTypes = "Property,Equipment",
                            EffectiveDate = new DateOnly(2025, 3, 1),
                            ExpirationDate = new DateOnly(2027, 2, 28),
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2025-002001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("127e03a8-ef89-cce5-1928-fe92094dfa60"),
                            ClientName = "Stanton Medical Group",
                            CoverageTypes = "Liability,Vehicle",
                            EffectiveDate = new DateOnly(2025, 1, 1),
                            ExpirationDate = new DateOnly(2026, 12, 31),
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2025-002002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("e39a965c-f3de-4b7d-be17-a46cffe0827e"),
                            ClientName = "Archived Corp",
                            CoverageTypes = "Property",
                            EffectiveDate = new DateOnly(2020, 1, 1),
                            ExpirationDate = new DateOnly(2021, 12, 31),
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2023-000099",
                            Status = "Expired"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ReserveHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ChangeSequence")
                        .HasColumnType("int");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("NewBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostingJobId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PreviousBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ReserveComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ReserveComponentId", "ChangeSequence")
                        .IsUnique();

                    b.ToTable("ReserveHistory", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Persistence.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "Key")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimDocument", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimParty", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", "Claim")
                        .WithMany("Parties")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimReserveComponent", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", "Claim")
                        .WithMany("ReserveComponents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimRiskObject", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", "Claim")
                        .WithMany("RiskObjects")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.LossEvent", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", "Claim")
                        .WithOne("LossEvent")
                        .HasForeignKey("ClaimsModule.Domain.Entities.LossEvent", "ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ReserveHistory", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.ClaimReserveComponent", "ReserveComponent")
                        .WithMany("History")
                        .HasForeignKey("ReserveComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReserveComponent");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Claim", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("LossEvent")
                        .IsRequired();

                    b.Navigation("Parties");

                    b.Navigation("ReserveComponents");

                    b.Navigation("RiskObjects");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimReserveComponent", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
